<?php
if (!isset($menuActive)) {
  $menuActive = '';
}
?>
<aside class="sidebar" id="sidebar">
  <div style="padding:8px 0 4px">
    <div class="sg-label">Chat <span class="sg-minus">-</span></div>
    <a class="nav-item <?php echo $menuActive === 'chat' ? 'active' : ''; ?>" href="/home.php">
      <svg viewBox="0 0 16 16" fill="none"><rect x="1" y="2" width="14" height="9" fill="currentColor" opacity=".25"/><rect x="1" y="2" width="14" height="2" fill="currentColor" opacity=".6"/><rect x="1" y="9" width="14" height="2" fill="currentColor" opacity=".45"/><rect x="1" y="4" width="2" height="5" fill="currentColor" opacity=".45"/><rect x="13" y="4" width="2" height="5" fill="currentColor" opacity=".45"/><rect x="3" y="5" width="5" height="2" fill="currentColor" opacity=".5"/><rect x="3" y="11" width="5" height="3" fill="currentColor" opacity=".4"/></svg>
      <span class="nav-lbl">Chat</span><span class="nav-badge">2</span>
    </a>
  </div>

  <div style="padding:4px 0">
    <div class="sg-label">Controle <span class="sg-minus">-</span></div>
    <a class="nav-item <?php echo $menuActive === 'overview' ? 'active' : ''; ?>" href="/overview"><svg viewBox="0 0 16 16" fill="none"><rect x="1" y="1" width="6" height="6" fill="currentColor" opacity=".4"/><rect x="9" y="1" width="6" height="6" fill="currentColor" opacity=".4"/><rect x="1" y="9" width="6" height="6" fill="currentColor" opacity=".4"/><rect x="9" y="9" width="6" height="6" fill="currentColor" opacity=".25"/><rect x="10" y="2" width="4" height="2" fill="var(--accent)" opacity=".7"/><rect x="2" y="10" width="4" height="4" fill="var(--green)" opacity=".4"/></svg><span class="nav-lbl">Visao Geral</span></a>
    <a class="nav-item <?php echo $menuActive === 'channels' ? 'active' : ''; ?>" href="/channels"><svg viewBox="0 0 16 16" fill="none"><rect x="1" y="7" width="14" height="2" fill="currentColor" opacity=".5"/><rect x="3" y="4" width="2" height="8" fill="currentColor" opacity=".5"/><rect x="11" y="4" width="2" height="8" fill="currentColor" opacity=".5"/><rect x="1" y="7" width="2" height="2" fill="var(--accent)" opacity=".8"/><rect x="13" y="7" width="2" height="2" fill="var(--green)" opacity=".8"/><rect x="7" y="7" width="2" height="2" fill="var(--yellow)" opacity=".8"/></svg><span class="nav-lbl">Canais</span></a>
    <a class="nav-item <?php echo $menuActive === 'instances' ? 'active' : ''; ?>" href="/instance.php"><svg viewBox="0 0 16 16" fill="none"><rect x="1" y="4" width="14" height="2" fill="currentColor" opacity=".5"/><rect x="1" y="4" width="2" height="8" fill="currentColor" opacity=".4"/><rect x="13" y="4" width="2" height="8" fill="currentColor" opacity=".4"/><rect x="1" y="10" width="14" height="2" fill="currentColor" opacity=".4"/><rect x="4" y="7" width="3" height="3" fill="currentColor" opacity=".5"/><rect x="9" y="7" width="3" height="3" fill="currentColor" opacity=".5"/><rect x="5" y="8" width="1" height="1" fill="var(--green)" opacity=".9"/><rect x="10" y="8" width="1" height="1" fill="var(--accent)" opacity=".9"/></svg><span class="nav-lbl">Instancias</span></a>
    <a class="nav-item <?php echo $menuActive === 'sessions' ? 'active' : ''; ?>" href="/sessions"><svg viewBox="0 0 16 16" fill="none"><rect x="2" y="1" width="12" height="14" fill="currentColor" opacity=".12"/><rect x="2" y="1" width="12" height="2" fill="currentColor" opacity=".5"/><rect x="2" y="1" width="2" height="14" fill="currentColor" opacity=".35"/><rect x="12" y="1" width="2" height="14" fill="currentColor" opacity=".35"/><rect x="2" y="13" width="12" height="2" fill="currentColor" opacity=".35"/><rect x="4" y="4" width="4" height="2" fill="currentColor" opacity=".4"/><rect x="4" y="7" width="7" height="2" fill="currentColor" opacity=".3"/></svg><span class="nav-lbl">Sessoes</span></a>
    <a class="nav-item <?php echo $menuActive === 'usage' ? 'active' : ''; ?>" href="/use.php"><svg viewBox="0 0 16 16" fill="none"><rect x="1" y="11" width="3" height="4" fill="currentColor" opacity=".5"/><rect x="5" y="7" width="3" height="8" fill="var(--accent)" opacity=".6"/><rect x="9" y="4" width="3" height="11" fill="currentColor" opacity=".5"/><rect x="13" y="1" width="3" height="14" fill="var(--green)" opacity=".6"/></svg><span class="nav-lbl">Uso</span></a>
    <a class="nav-item <?php echo $menuActive === 'cron' ? 'active' : ''; ?>" href="/cron.php"><svg viewBox="0 0 16 16" fill="none"><rect x="2" y="2" width="12" height="12" fill="currentColor" opacity=".1"/><rect x="2" y="2" width="12" height="2" fill="currentColor" opacity=".45"/><rect x="3" y="4" width="2" height="2" fill="var(--red)" opacity=".7"/><rect x="7" y="4" width="2" height="2" fill="var(--yellow)" opacity=".7"/><rect x="11" y="4" width="2" height="2" fill="var(--green)" opacity=".7"/><rect x="4" y="9" width="4" height="2" fill="currentColor" opacity=".4"/></svg><span class="nav-lbl">Tarefas Cron</span></a>
  </div>

  <div class="px-div"></div>

  <div style="padding:4px 0">
    <div class="sg-label">Agente <span class="sg-minus">-</span></div>
    <a class="nav-item <?php echo $menuActive === 'agents' ? 'active' : ''; ?>" href="/agents"><svg viewBox="0 0 16 16" fill="none"><rect x="4" y="2" width="8" height="2" fill="currentColor" opacity=".5"/><rect x="2" y="4" width="12" height="6" fill="currentColor" opacity=".15"/><rect x="2" y="4" width="2" height="6" fill="currentColor" opacity=".4"/><rect x="12" y="4" width="2" height="6" fill="currentColor" opacity=".4"/><rect x="5" y="6" width="2" height="2" fill="currentColor" opacity=".6"/><rect x="9" y="6" width="2" height="2" fill="currentColor" opacity=".6"/><rect x="4" y="10" width="2" height="3" fill="currentColor" opacity=".35"/><rect x="10" y="10" width="2" height="3" fill="currentColor" opacity=".35"/></svg><span class="nav-lbl">Agentes</span></a>
    <a class="nav-item <?php echo $menuActive === 'skills' ? 'active' : ''; ?>" href="/skills.php"><svg viewBox="0 0 16 16" fill="none"><rect x="7" y="1" width="2" height="3" fill="var(--accent-bright)" opacity=".7"/><rect x="10" y="3" width="3" height="2" fill="var(--accent-bright)" opacity=".6"/><rect x="12" y="6" width="2" height="4" fill="var(--accent-bright)" opacity=".5"/><rect x="10" y="11" width="3" height="2" fill="var(--accent-bright)" opacity=".5"/><rect x="7" y="12" width="2" height="3" fill="var(--accent-bright)" opacity=".45"/><rect x="3" y="11" width="3" height="2" fill="var(--accent-bright)" opacity=".45"/><rect x="2" y="6" width="2" height="4" fill="var(--accent-bright)" opacity=".5"/><rect x="3" y="3" width="3" height="2" fill="var(--accent-bright)" opacity=".6"/><rect x="6" y="6" width="4" height="4" fill="var(--accent)" opacity=".5"/></svg><span class="nav-lbl">Habilidades</span></a>
    <a class="nav-item <?php echo $menuActive === 'nodes' ? 'active' : ''; ?>" href="/nos.php"><svg viewBox="0 0 16 16" fill="none"><rect x="1" y="6" width="4" height="4" fill="currentColor" opacity=".5"/><rect x="6" y="1" width="4" height="4" fill="currentColor" opacity=".5"/><rect x="11" y="6" width="4" height="4" fill="currentColor" opacity=".5"/><rect x="6" y="11" width="4" height="4" fill="currentColor" opacity=".5"/><rect x="7" y="7" width="2" height="2" fill="var(--accent)" opacity=".8"/></svg><span class="nav-lbl">N&oacute;s</span></a>
  </div>

  <div class="px-div"></div>

  <div style="padding:4px 0">
    <div class="sg-label">Configuracoes <span class="sg-minus">-</span></div>
    <a class="nav-item <?php echo ($menuActive === 'config' || $menuActive === 'settings') ? 'active' : ''; ?>" href="/settings"><svg viewBox="0 0 16 16" fill="none"><rect x="6" y="5" width="4" height="4" fill="currentColor" opacity=".65"/><rect x="7" y="6" width="2" height="2" fill="#07030f"/><rect x="5" y="1" width="6" height="2" fill="currentColor" opacity=".5"/><rect x="3" y="3" width="2" height="2" fill="currentColor" opacity=".5"/><rect x="11" y="3" width="2" height="2" fill="currentColor" opacity=".5"/><rect x="1" y="5" width="2" height="4" fill="currentColor" opacity=".5"/><rect x="13" y="5" width="2" height="4" fill="currentColor" opacity=".5"/></svg><span class="nav-lbl">Config</span></a>
    <a class="nav-item <?php echo $menuActive === 'plans' ? 'active' : ''; ?>" href="/plans.php"><svg viewBox="0 0 16 16" fill="none"><rect x="1" y="3" width="14" height="10" fill="currentColor" opacity=".14"/><rect x="1" y="3" width="14" height="2" fill="currentColor" opacity=".45"/><rect x="1" y="3" width="2" height="10" fill="currentColor" opacity=".35"/><rect x="13" y="3" width="2" height="10" fill="currentColor" opacity=".35"/><rect x="3" y="6" width="3" height="5" fill="var(--green)" opacity=".45"/><rect x="7" y="6" width="3" height="5" fill="var(--accent)" opacity=".55"/><rect x="11" y="6" width="3" height="5" fill="var(--yellow)" opacity=".55"/></svg><span class="nav-lbl">Plans</span></a>
    <a class="nav-item <?php echo $menuActive === 'logs' ? 'active' : ''; ?>" href="/logs"><svg viewBox="0 0 16 16" fill="none"><rect x="1" y="2" width="14" height="3" fill="currentColor" opacity=".4"/><rect x="1" y="5" width="2" height="9" fill="currentColor" opacity=".35"/><rect x="13" y="5" width="2" height="9" fill="currentColor" opacity=".35"/><rect x="1" y="12" width="14" height="2" fill="currentColor" opacity=".35"/><rect x="3" y="3" width="2" height="1" fill="var(--red)" opacity=".8"/><rect x="6" y="3" width="2" height="1" fill="var(--yellow)" opacity=".8"/><rect x="9" y="3" width="2" height="1" fill="var(--green)" opacity=".8"/><rect x="3" y="7" width="4" height="1" fill="var(--green)" opacity=".6"/></svg><span class="nav-lbl">Logs</span></a>
    <a class="nav-item <?php echo $menuActive === 'api_docs' ? 'active' : ''; ?>" href="/api-docs.php"><svg viewBox="0 0 16 16" fill="none"><rect x="2" y="1" width="10" height="14" fill="currentColor" opacity=".12"/><rect x="2" y="1" width="10" height="2" fill="currentColor" opacity=".5"/><rect x="2" y="1" width="2" height="14" fill="currentColor" opacity=".4"/><rect x="10" y="1" width="2" height="14" fill="currentColor" opacity=".35"/><rect x="2" y="13" width="10" height="2" fill="currentColor" opacity=".35"/><rect x="4" y="4" width="6" height="1" fill="currentColor" opacity=".45"/><rect x="4" y="6" width="4" height="1" fill="currentColor" opacity=".35"/><rect x="12" y="3" width="2" height="10" fill="var(--accent)" opacity=".5"/></svg><span class="nav-lbl">API Docs</span></a>
  </div>

  <div class="sb-bottom">
    <div class="sb-avatar" id="sbAvatar">U</div>
    <div style="flex:1;min-width:0"><span class="sb-name" id="sbName">VexusUser</span><span class="sb-status" id="sbStatus">online</span></div>
  </div>
</aside>
