import { SurfaceCard } from "@vexus/ui";

import { PageHeader } from "../../../components/page-header";

export default function MemoryPage() {
  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="Memory"
        title="Workspace knowledge plane"
        description="Inspect facts, notes, summaries and file assets tied to workspaces, agents and sessions."
      />

      <div className="grid gap-4 lg:grid-cols-3">
        {[
          ["Persistent facts", "124", "Business-critical data retained across sessions."],
          ["File assets", "36", "Uploaded PDFs, briefs and operator notes."],
          ["Recent writes", "18", "New memory items generated by agent activity."]
        ].map(([label, value, description]) => (
          <SurfaceCard key={label}>
            <p className="text-xs uppercase tracking-[0.24em] text-slate-400">{label}</p>
            <p className="mt-4 text-3xl font-semibold text-white">{value}</p>
            <p className="mt-2 text-sm leading-6 text-slate-300">{description}</p>
          </SurfaceCard>
        ))}
      </div>

      <SurfaceCard className="space-y-4">
        <p className="text-xs uppercase tracking-[0.24em] text-slate-400">Recent memory events</p>
        <div className="space-y-3">
          {[
            "Saved pricing objection pattern for Lead Qualifier.",
            "Attached product brief to workspace knowledge base.",
            "Stored follow-up preference note for active WhatsApp session."
          ].map((item) => (
            <div key={item} className="rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3 text-sm text-slate-200">
              {item}
            </div>
          ))}
        </div>
      </SurfaceCard>
    </div>
  );
}
